### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ferambot**
Hi, I am Feram,

I'm a bot and I work on behalf of [Adrian][adius].
If my merge request helped to improve this repository,
please consider to [star my repo][repo] to show some love! 😊

If I didn't behave, you can [create an issue][issues]
and my dad will try to fix me.

Love, hugs and kisses,
your [Feram][feram]

[adius]: https://github.com/adius
[feram]: https://github.com/ferambot
[repo]: https://github.com/ferambot/feram
[issues]: https://github.com/ferambot/feram/issues

### CODE REVIEW

**Comment by adewes** [comment]
Nice work @adius! What kind of things does the bot fix? Does it perform syntatic / semantic analysis of the code as well?

**Comment by adius** [comment]
Thanks! 😊
Not yet, but we're working on it!
If you're interested, you can sign up for our newsletter on [feram.co](http://feram.co) to get updates about new features.
(No spam … I promise 😉)

**Comment by adius** [comment]
We also hope to establish a platform for helpful open-source modules for Feram on @feramhq . It's going to be awesome! 😁

**Comment by adewes** [comment]
Sure sounds interesting! I have been working on technologies for code analysis & re-engineering for the past two years, always curious to see what other people are doing in the field.

**Comment by adius** [comment]
😂 Haha, oh yeah, I just realized you are the cofounder of Quantified Code. What a coincidence 😁. (Feram chooses repos randomly)
What has Quantified Code been up to lately anyways? It looks a little deserted ... is it still a thing?

**Comment by adewes** [comment]
@adius sent you an e-mail to your GH address

**Pull request merged**
